services:
  app:
    build:
      context: . 
    env_file:
      - .env 
    depends_on:
      - redis-cache
    volumes:
      - ./logs:/app/logs
  redis-cache:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data: 