services:
  nginx:
    image: nginx:1.29
    container_name: anant_nginxx
    ports: 
        - "8888:80"
    volumes:
      - ./webPage:/usr/share/nginx/html:ro

  ubuntu:
    image: ubuntu:22.04
    container_name: anant_ubuntu
    command: /bin/bash -c "apt-get update && apt-get install -y curl && sleep infinity"
   
