services:
  nginx:
    image: nginx:1.29
    container_name: anant_nginxx
    ports: 
        - "8888:80"
    volumes:
      - ./webPage:/usr/share/nginx/html:ro
    networks:
      - common_net

  ubuntu:
    image: ubuntu:22.04
    container_name: anant_ubuntu
    command: sleep infinity
    networks:
      - common_net

networks:
  common_net:
    driver: bridge
