services:
  nginx:
    image: nginx:1.29
    container_name: anant_nginxx
    ports:
        - "8888:80"
    volumes:
      - ./webPage:/usr/share/nginx/html:ro
    networks:
      - common_net

  ubuntu:
    image: ubuntu:22.04
    container_name: anant_ubuntu
    volumes: 
            - ./saved_html:/saved_html
    command: >
      sh -c "apt-get update && 
             apt-get install -y curl &&
             curl http://nginx/index.html -o /saved_html/index_saved.txt && cat /saved_html/index_saved.txt &&
             sleep 30 && exit 0"
    depends_on:
      - nginx

    networks:
      - common_net

networks:
  common_net:
    driver: bridge

