nodes:
  - name: joiner
    processor: processors.join_two_lines.JoinEveryTwoLines

  - name: tagger
    processor: processors.tag_error.TagError

  - name: line_counter
    processor: processors.line_counter.LineCounter

  - name: snake_formatter
    processor: processors.snake.to_snakecase

  - name: upper_formatter
    processor: processors.upper.to_uppercase

routes:
  # Joiner → Tagger
  - from: joiner
    tag: default
    to: [tagger]

  # Tagger branches:
  - from: tagger
    tag: error
    to: [line_counter]

  - from: tagger
    tag: general
    to: []

  # Snake formatter branch:
  - from: snake_formatter
    tag: default
    to: [upper_formatter]

  - from: upper_formatter
    tag: default
    to: []

  # Line counter branch:
  - from: line_counter
    tag: default
    to: []
