[project]
name = "ex-basics-1-aganitha-anant-hello"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.16.1",
]

[tool.uv]
publish-url = "https://test.pypi.org/legacy/"
